### ISSUE TITLE
How to change color pallete?

### ISSUE THREAD

**Issue by KTsarlz** [Matt-McConway/mercurious-syntax#1]
Greate syntax btw!

**Comment by Matt-McConway** [comment]
Thanks :) 

The theme is based on the colour palette that I use for the website of my business. This is shown in the README file. 

- To change the colours you will need to edit the colours.less file. 
- To change what the colours are used for, you'll need to edit the syntax-variables.less and base.less files.

More info can be found [here](http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/).

Feel free to fork the project and make your own changes though :)
